### ISSUE TITLE
Rotated layers not butted/spaced correctly

### ISSUE THREAD

**Issue by ShaneNZ** [pberrecloth/butter-sketch-plugin#13]
Layers are butted/spaced based on the unrotated bounding box. To create the issue, create three tall, narrow boxes:
![image](https://user-images.githubusercontent.com/2524502/29549672-a3187876-875d-11e7-8412-ecaf63b3ca25.png)
Rotate the middle one 90 degrees:
![image](https://user-images.githubusercontent.com/2524502/29549685-b4906154-875d-11e7-9d6d-fca4fa9345bc.png)
When you butt them together, you get this:
![image](https://user-images.githubusercontent.com/2524502/29549707-d12a2408-875d-11e7-92af-2ebd9ec69749.png)
I would expect this:
![image](https://user-images.githubusercontent.com/2524502/29549717-e23d1ef8-875d-11e7-8209-1a0216c32f6e.png)

**Comment by ShaneNZ** [comment]
Looks like this runs through the issue.

http://sketchplugins.com/d/67-how-to-get-the-bounding-rectangle-of-a-layer-shape

**Comment by DWilliames** [comment]
Ah, good catch @ShaneNZ. Thanks for that! I'll get onto it now.

**Comment by DWilliames** [comment]
@ShaneNZ I think I have a fix for this now.
However, the behaviour is a little different to how you said you would expect it...

With an arrangement like so:

![](https://user-images.githubusercontent.com/6570446/29561619-7cb4d546-8779-11e7-8d82-4be1076b50be.png)

After 'butting' all the layers 'up' it would look like this:

![](https://user-images.githubusercontent.com/6570446/29561676-b1b6274a-8779-11e7-9b84-96cffb161784.png)

This is because when sorting the layers as to which should be first, it checks to see which has a point which is the most 'up'. Since the rotated layer sticks up above the rest, it is ordered first, followed by the next two.

Does that solution sound okay to you?

**Comment by ShaneNZ** [comment]
Yes, it does. On thinking about it, it's more natural than my original
expectation. Good work :)

**Comment by DWilliames** [comment]
Perfect. Thanks @ShaneNZ. I just released an update with the fix.
